// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/prasanth-pn/GolangAuthenticationWithTwilioJWT/pkg/api"
	"github.com/prasanth-pn/GolangAuthenticationWithTwilioJWT/pkg/api/handler"
	"github.com/prasanth-pn/GolangAuthenticationWithTwilioJWT/pkg/db"
	"github.com/prasanth-pn/GolangAuthenticationWithTwilioJWT/pkg/repository"
	"github.com/prasanth-pn/GolangAuthenticationWithTwilioJWT/pkg/usecase"
)

// Injectors from wire.go:

func InitializeEvent() (*http.ServeHTTP, error) {
	sqlDB := db.ConnectDB()
	authrepositoryinterface := repository.NewAuthRepository(sqlDB)
	authusecase := usecase.NewAuthUsecase(authrepositoryinterface)
	authHandler := handler.NewAuthHandler(authusecase)
	serveHTTP := http.NewServeHTTP(authHandler)
	return serveHTTP, nil
}
